development: &development
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  host: localhost
  database: synchrotron2_dev
  
test:
  <<: *development
  database: synchrotron2_test

production:
  encoding: utf8
  timeout: 5000
